on:
  push:
    tags:
      - v**

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: johngu9/ubuntu:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Generate random ssl cart and key
        run: openssl req -nodes -new -x509  -keyout server.key -out server.crt -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=CommonNameOrHostname"
        working-directory: rust/src/tls

      - name: Build Project
        run: npm run build

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: web_ssh_tool_ubuntu
          path: rust/target/release/rust

  build-macos:
    runs-on: "macos-latest"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install OpenSSL
        run: brew install openssl

      - name: Generate random ssl cart and key
        run: openssl req -nodes -new -x509  -keyout server.key -out server.crt -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=CommonNameOrHostname"
        working-directory: rust/src/tls

      - name: Build Project
        run: npm run build

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: web_ssh_tool_macos
          path: rust/target/release/rust
